"""
FastAPI middleware for request tracking and performance monitoring.

This module provides request IDs, request logging, response-time
measurement, and error logging for API requests.
"""

import logging
import time
import uuid

from fastapi import Request
from starlette.middleware.base import BaseHTTPMiddleware
from app.core.metrics import Metrics

logger = logging.getLogger(__name__)
metrics=Metrics()


class RequestLoggingMiddleware(BaseHTTPMiddleware):
    """
    Middleware that tracks API requests and response performance.

    Each request receives a unique request ID. The middleware logs
    the HTTP method, request path, response status, and processing time.
    """

    async def dispatch(self, request: Request, call_next):
        """
        Process an HTTP request and record monitoring information.

        Args:
            request: Incoming FastAPI request.
            call_next: Callable that forwards the request to the next
                middleware or route handler.

        Returns:
            Response: HTTP response generated by the application.
        """
        request_id = str(uuid.uuid4())
        start_time = time.perf_counter()

        request.state.request_id = request_id

        logger.info(
            "Request started | request_id=%s | method=%s | path=%s",
            request_id,
            request.method,
            request.url.path,
        )

        try:
            response = await call_next(request)


            duration = time.perf_counter() - start_time

            metrics.record_request(
                response_time=duration,
                success=response.status_code < 400,
            )

            response.headers["X-Request-ID"] = request_id

            logger.info(
                (
                    "Request completed | request_id=%s | "
                    "method=%s | path=%s | status=%s | duration=%.4fs"
                ),
                request_id,
                request.method,
                request.url.path,
                response.status_code,
                duration,
            )

            return response

        except Exception:
            duration = time.perf_counter() - start_time
            metrics.record_request(
                response_time=duration,
                success=False,
            )
            logger.exception(
                (
                    "Request failed | request_id=%s | "
                    "method=%s | path=%s | duration=%.4fs"
                ),
                request_id,
                request.method,
                request.url.path,
                duration,
            )

            raise